apiVersion: v1
kind: Pod
metadata:
  name: nginx-postgres-pod
  labels:
    app: nginx-postgres

spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80