version: "3.8"

services:
    app:build:
      context: .
      dockerfile: Dockerfile

      ports:
        - "3000:3000"
      depends_on:
      - db
    
    db:
      image: "postgres"

      enviroment:
        POSTGRES_PASSWORD: admin123
      
      ports:
        "5432:5432"
      